### ISSUE TITLE
pretrained file and enet_unpooling_best.h5 missing?

### ISSUE THREAD

**Issue by declanzane** [PavlosMelissinos/enet-keras#15]
Hi, 
  when I run the predict.py and train.sh, it said that can't find "enet_unpooling_best.h5 " and "pretrained/torch_enet.pkl". And I can't find the two files in the folder either. So  what's wrong with it?
 Thanks!

**Comment by PavlosMelissinos** [comment]
1. For training, you need to run [`python from_torch.py`](https://github.com/PavlosMelissinos/enet-keras/blob/master/src/models/from_torch.py) in order to create the pickle file with the network weights (I've done it this way for transparency).

2. For prediction you need to have trained model first. I haven't provided one because I'm not getting good (quantitative) results on mscoco. So it makes sense that you get that error. If you want to do prediction, you could either train from scratch (definitely won't get you good results), or you could load the weights from torch except for the last one, freeze most of the layers and let the top ones do all the work (should be pretty fast)

The documentation is incomplete so you're right to be confused, but in the next few days I'll merge the datasets_overhaul and icnet branches and update the readme so hopefully it will be more straightforward.

**Comment by declanzane** [comment]
All right. Thanks for the detailed reply and look forward to the update!@PavlosMelissinos

**Comment by PavlosMelissinos** [comment]
Hey there!

Check it out again if you will, I've reorganized the project and updated the documentation, so hopefully it's not as bad now. Thanks!

The instructions work on my end without any hiccup so I'm closing the issue for now. Of course feel free to reopen it and let me know if there's any problem.
