### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by subhacom** [PavlosMelissinos/enet-keras#33]
Pip throws and error on the line containing: `gsutil=4.46` which seems to be a typo in  `requirements.txt` . The same issue appears in `environment.yml` when using conda to install the dependencies.
Other than that, many of these dependencies seem to be on out-dated versions. Is there any other recommended way to get the installation to work with more recent packages?

**Comment by PavlosMelissinos** [comment]
Yeah it's a typo, that should be a double equals sign in both files (i.e. `gsutil==4.46`), sorry about that.

It should be fine now but let me know if you encounter any problems.

Thanks for reporting the bug! :)

_By the way_, I'm really curious how you ended up here... ENet is a 2016 architecture and this repo has not really been active since 2017. I'd imagine there would be easier, better and faster ways to do semantic segmentation by now! What gives?

**Comment by subhacom** [comment]
Thanks for the prompt response, and for maintaining this project all these years. 

I am really an outsider, just getting my feet wet with modern ML tools. Some sequence of google searches for image segmentation and keras landed me here. In particular, the enet paper shows up quite early in the search, and the authors' github page directs here for keras version.

**Comment by PavlosMelissinos** [comment]
Cool!

You might have heard this before but (in case you haven't) bear in mind that:
1. Semantic image segmentation miiiight not be the best application of deep learning to get your feet wet with (in essence it's more granular/complex object detection, which is more granular image classification) and
2. the project assumes that you have a decent GPU (for instance, a 8GB GTX1070 should be fine).

Let me know if there's anything else.

Cheers
