### ISSUE TITLE
MaxUnpooling in the decoder

### ISSUE THREAD

**Issue by MarcoDalFarra** [PavlosMelissinos/enet-keras#4]
Have you tried to implement the MaxUnpooling operation that the original ENet uses instead of using the UpSampling Layer?

**Comment by PavlosMelissinos** [comment]
Nice catch!

First of all, I tend to agree with Geoff Hinton when [he says that it's a disaster that pooling works in CNNs](https://www.reddit.com/r/MachineLearning/comments/2lmo0l/ama_geoffrey_hinton/clyj4jv/?context=1).

However, I've tried implementing unpooling on another project that is currently not public. Making it work on keras though was too dirty and I don't think it's that effective so I'm not sure it's worth the effort.

Instead of using that, I've been playing with the idea of dilated convolutions instead of pooling and subpixel convolutions instead of unpooling/upsampling/deconvolution operations.

However, having the original setup is important for result reproduction during evaluation so I'll consider pushing an alternative version of enet with the original unpooling operation if you'd be interested in that (I have to warn you that it's ugly though).

**Comment by MarcoDalFarra** [comment]
I'd be very much interested in seeing your solution. I've tried it myself, mainly using ideas from https://github.com/tensorflow/tensorflow/issues/2169, but I never got it to work properly.

**Comment by PavlosMelissinos** [comment]
Ok, [gist is up](https://gist.github.com/PavlosMelissinos/6ddb1ba86f51214477a76ce670d18c97) with just the unpooling code so you can have a look or add it to your code until I find some time to add it to the project. It's been a while since I wrote that and can definitely be improved so feel free to ask anything and do whatever you want with it.

**Comment by PavlosMelissinos** [comment]
Thanks for the 🎉 ! [Check again](https://gist.github.com/PavlosMelissinos/6ddb1ba86f51214477a76ce670d18c97), I've added a few lines in a different file to demonstrate usage.

**Comment by PavlosMelissinos** [comment]
Any luck @MarcoDalFarra? Did it work?

**Comment by MarcoDalFarra** [comment]
I haven't tried it yet. Right now I'm looking into this new paper: https://arxiv.org/abs/1704.08545v1 - but I will let you know, when I'm giving it a go. Perhaps in the coming week :)

**Comment by MarcoDalFarra** [comment]
So I got it to work. I still need to run a few tests, but it seems like the predictions do indeed get sharper boundaries for the objects as expected. At least compared to my old approach, which was to always unpool by placing the max element in the top left corner. I haven't tested the performance implications, but that is on my next to do. Thank you very much for your help!

**Comment by PavlosMelissinos** [comment]
Nice! I'm glad it worked. :)

**Comment by PavlosMelissinos** [comment]
A (slightly nicer) version of the network with unpooling is now available (src/models/enet_unpooling)!

1. Using tf.nn.max_pool_with_argmax to get both the values and the indices at once instead of splitting the tasks to two different layers.
2. Unpooling2D using tf.scatter_nd instead of UpSampling2D and tf.where.

**Comment by mrgloom** [comment]
Looks like this trick can be used to get max pooling indices:
https://github.com/keras-team/keras/blob/4f2e65c385d60fa87bb143c6c506cbe428895f44/examples/mnist_swwae.py#L90

**Comment by PavlosMelissinos** [comment]
This project has been on hold for quite some time but that's good to know, thanks!
